import { useState, useCallback } from "react";
import { useWallet } from "../lib/context";

export function AccountDetails() {
  const { activeAccount, removeAccount, network } = useWallet();
  const [showKey, setShowKey] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  if (!activeAccount) return null;

  const copyToClipboard = async (text: string, label: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const printAccountPdf = () => {
    const w = window.open("", "_blank", "width=800,height=600");
    if (!w) return;

    const now = new Date().toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit",
    });

    w.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>Solen Wallet - ${activeAccount.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace; padding: 48px; color: #1a1a2e; background: #fff; }
    .header { display: flex; align-items: center; gap: 12px; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 2px solid #10b981; }
    .logo { font-size: 24px; font-weight: 700; }
    .logo span:first-child { color: #10b981; }
    .logo span:last-child { color: #666; font-weight: 400; }
    .subtitle { font-size: 12px; color: #888; margin-top: 4px; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-bottom: 6px; }
    .value { font-family: "SF Mono", "Fira Code", "Consolas", monospace; font-size: 12px; word-break: break-all; background: #f5f5f5; padding: 10px 12px; border-radius: 6px; border: 1px solid #e0e0e0; }
    .secret { background: #fff5f5; border-color: #fecaca; color: #b91c1c; }
    .warning { margin-top: 32px; padding: 12px 16px; background: #fffbeb; border: 1px solid #fde68a; border-radius: 6px; font-size: 11px; color: #92400e; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 10px; color: #aaa; display: flex; justify-content: space-between; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo"><span>Solen</span><span>Wallet</span></div>
      <div class="subtitle">Account Backup &middot; ${now}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Account Name</div>
    <div class="value">${activeAccount.name}</div>
  </div>

  <div class="section">
    <div class="section-title">Network</div>
    <div class="value">${network}</div>
  </div>

  <div class="section">
    <div class="section-title">Account ID</div>
    <div class="value">${activeAccount.accountId}</div>
  </div>

  <div class="section">
    <div class="section-title">Public Key</div>
    <div class="value">${activeAccount.publicKey}</div>
  </div>

  <div class="section">
    <div class="section-title">Secret Key (Private)</div>
    <div class="value secret">${activeAccount.secretKey.slice(0, 64)}</div>
  </div>

  <div class="warning">
    <strong>KEEP THIS DOCUMENT SAFE.</strong> Anyone with your secret key has full control of your account.
    Store this in a secure location and do not share it. Consider destroying this printout after backing up to a secure offline location.
  </div>

  <div class="footer">
    <span>Solen Blockchain &middot; solenchain.io</span>
    <span>Generated by Solen Wallet v0.1.0</span>
  </div>
</body>
</html>`);
    w.document.close();
    w.print();
  };

  const CopyIcon = ({ label }: { label: string }) =>
    copied === label ? (
      <svg className="w-4 h-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
      </svg>
    ) : (
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
      </svg>
    );

  return (
    <div className="bg-gray-800/50 rounded-2xl p-6 border border-gray-700/50">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-200">Account Details</h3>
        <button
          onClick={printAccountPdf}
          title="Print / Save as PDF"
          className="flex items-center gap-1.5 text-sm bg-gray-700 hover:bg-gray-600 text-gray-300 px-3 py-1.5 rounded-lg transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          Print Backup
        </button>
      </div>

      <div className="space-y-3">
        <div>
          <div className="text-xs text-gray-500 mb-1">Account ID</div>
          <div className="flex items-center gap-2">
            <code className="text-sm text-gray-300 font-mono break-all flex-1">
              {activeAccount.accountId}
            </code>
            <button
              onClick={() => copyToClipboard(activeAccount.accountId, "id")}
              className="text-gray-500 hover:text-gray-300 shrink-0"
            >
              <CopyIcon label="id" />
            </button>
          </div>
        </div>

        <div>
          <div className="text-xs text-gray-500 mb-1">Public Key</div>
          <div className="flex items-center gap-2">
            <code className="text-sm text-gray-300 font-mono break-all flex-1">
              {activeAccount.publicKey}
            </code>
            <button
              onClick={() => copyToClipboard(activeAccount.publicKey, "pub")}
              className="text-gray-500 hover:text-gray-300 shrink-0"
            >
              <CopyIcon label="pub" />
            </button>
          </div>
        </div>

        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs text-gray-500">Secret Key</span>
            <button
              onClick={() => setShowKey(!showKey)}
              className="text-xs text-gray-500 hover:text-gray-300"
            >
              {showKey ? "Hide" : "Show"}
            </button>
          </div>
          {showKey && (
            <div className="flex items-center gap-2">
              <code className="text-sm text-red-400 font-mono break-all flex-1">
                {activeAccount.secretKey.slice(0, 64)}
              </code>
              <button
                onClick={() => copyToClipboard(activeAccount.secretKey.slice(0, 64), "sec")}
                className="text-gray-500 hover:text-gray-300 shrink-0"
              >
                <CopyIcon label="sec" />
              </button>
            </div>
          )}
        </div>

        <div className="pt-3 border-t border-gray-700/50">
          <button
            onClick={() => {
              if (confirm(`Remove account "${activeAccount.name}"? This cannot be undone.`)) {
                removeAccount(activeAccount.accountId);
              }
            }}
            className="text-sm text-red-400 hover:text-red-300 transition-colors"
          >
            Remove Account
          </button>
        </div>
      </div>
    </div>
  );
}
